# Primary Colors
foreground              #78c9eb
background              #120B10
cursor                  #FFDF00
selection_foreground    #120B10
selection_background    #FFDF00

visual_bell_color               none

#: Tab bar colors
active_tab_foreground           #120B10
active_tab_background           #FFDF00
inactive_tab_foreground         #228B22
inactive_tab_background         #120B10
tab_bar_background              #120B10
tab_bar_margin_color            #120B10

#: The basic 16 colors

#: black
color0 #000000
color8 #777777

#: red (Sky Blue accent)
ccolor1 #78c9eb
color9  #B0E2FF

#: green (Mapped to files / executables)
color2  #FFDF00
color10 #FFDF00

#: yellow
color3  #F4EF00
color11 #FFFC58

#: blue (Mapped to folders)
color4  #27a127
color12 #27a127

#: magenta
color5  #D57BFF
color13 #C592FF

#: cyan
color6  #0DCDCD
color14 #00FFC8

#: white
color7  #EEFFFF
color15 #FFFFFF
