# This is the recommended settings in hyprland.conf to match my theme.
# You can ignore this if you want to configure your own.

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 3

    col.active_border = rgb(FFDF00)
    col.inactive_border = rgb(FFBF00)
  }

decoration {
    rounding = 10
    rounding_power = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 0.75
    inactive_opacity = 0.80

    shadow {
        enabled = true
        range = 5
        render_power = 1
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 15                       # Increased for a more noticeable blur
        passes = 2                      # More passes make the blur smoother
        ignore_opacity = true
        vibrancy = 0.15s
        new_optimizations = true        # Essential for performance when using multiple passes
        contrast = 1.50
        brightness = 0.75
    }
